### PR TITLE
Did little improvments of preforments

### PR DESCRIPTION
**Pull request by KristiyanDinev**
removed YES and NO and improved while loops.

### CODE REVIEW

**Comment by TheGhostRoot** [comment]
No

**Comment by mouadessalim** [comment]
Thanks for contributing, i am gonna check the improvements when i am free.

Appreciate it ! 👍

**Comment by TheGhostRoot** [comment]
No prolem. I can't beleve how easy it is to get somone's account just by QR code XD .

**Comment by mouadessalim** [comment]
Yeah it's kinda easy when you read the code, but to produce it and find where the token is saved in your web browser, it's another story. By de way it's not working proprely, discord just added a fire wall system checking you location country so if you try to qr grab someone living in another country than yours it's not gonna work. But don't worry i am working on a way to bypass it.

**Comment by TheGhostRoot** [comment]
Can't you use proxies or it doesn't work in that way?

**Comment by mouadessalim** [comment]
It's exactly what i am planning to set up after my exams (actually a med strudent)

**Comment by TheGhostRoot** [comment]
I know how to setup proxies, but it will work only on debian based OS. I can help you with this, but can you merge the commits?

**Pull request merged**
